# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginR', '0003_poke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='pokes',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='users',
        ),
        migrations.AddField(
            model_name='poke',
            name='poked',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poked', to='loginR.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poke',
            name='poker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poker', to='loginR.User'),
            preserve_default=False,
        ),
    ]
